# Generated by Django 3.2.8 on 2021-10-31 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование блюда')),
                ('comments', models.TextField(verbose_name='Описание блюда')),
            ],
            options={
                'verbose_name': 'Блюда',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиенты',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование единицы измерения')),
            ],
            options={
                'verbose_name': 'Единицы измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(verbose_name='Количество ингредиентов')),
                ('cook_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_app.cookname', verbose_name='Блюдо')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_app.ingredients', verbose_name='Ингредиент')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_app.units', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Рецепты',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
